[package]
name = "actix-server"
version = "0.1.0"
authors = ["Scott Nicholes <scott93gps@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
